#' @title Output Parser for GENIE3
#' @description This function parses the standard output generated by the BEELINE tool GENIE3.
#' @param filename a file path to the GENIE3 output file generated by BEELINE.
#' @author Ilias Moutsopoulos
#' @examples
#' # path to GENIE3 output file
#' genie3_output <- system.file('beeline_examples/GENIE3/outFile.csv', package = 'edgynode')
#' # import GENIE3 specific output
#' genie3_parsed <- import_genie3(genie3_output)
#' # look at output
#' head(genie3_parsed)
#' @export

import_genie3 <- function(filename) {
  as.matrix(read.csv(filename, row.names = 1, check.names = FALSE))
}
