#' @title Output Parser for GRISLI
#' @description This function parses the standard output generated by the BEELINE tool GRISLI.
#' @param file_path a file path to the GRISLI output file generated by BEELINE.
#' @author Sergio Vasquez and Hajk-Georg Drost
#' @examples
#' # path to GRISLI output file
#' grisli_output <- system.file('beeline_examples/GRISLI/outFile.txt', package = 'edgynode')
#' # import GENIE3 specific output
#' grisli_parsed <- grisli(grisli_output)
#' # look at output
#' head(grisli_parsed)
#' @export

grisli <- function(file_path) {
  if (!file.exists(file_path))
    stop("Please specify a valid file path to ", file_path, "...", .call = FALSE)
  
  GRISLI_output <-
    suppressMessages(suppressWarnings(
      readr::read_delim(
        file = file_path,
        col_names = TRUE,
        delim = ","
      )
    ))
  colnames(GRISLI_output) <- rownames(GRISLI_output)
  
  return(GRISLI_output)
}