#' @title Output Parser for GENIE3
#' @description This function parses the standard output generated by the BEELINE tool GENIE3.
#' @param file_path a file path to the GENIE3 output file generated by BEELINE.
#' @author Sergio Vasquez and Hajk-Georg Drost
#' @examples
#' # path to GENIE3 output file
#' genie3_output <- system.file('beeline_examples/GENIE3/outFile.csv', package = 'scNetworkR')
#' # import GENIE3 specific output
#' genie3_parsed <- genie(genie3_output)
#' # look at output
#' head(genie3_parsed)
#' @export

genie <- function(file_path) {
  if (!file.exists(file_path))
    stop("Please specify a valid file path to ", file_path, "...", .call = FALSE)

  GENIE3_output <-
    suppressMessages(suppressWarnings(
      readr::read_delim(
        file = file_path,
        col_names = TRUE,
        delim = ","
      )
    ))
  names(GENIE3_output)[1] <- "rowname"
  res <- tibble::column_to_rownames(GENIE3_output)

  return(data.matrix(res))
}
