#' @title Output Parser for PIDC
#' @description This function parses the standard output generated by the BEELINE tool PIDC.
#' @param file_path a file path to the PIDC output file generated by BEELINE.
#' @author Sergio Vasquez and Hajk-Georg Drost
#' @examples
#' # path to PIDC output file
#' pidc_output <- system.file('beeline_examples/PIDC/outFile.txt', package = 'edgynode')
#' # import PIDC specific output
#' pidc_parsed <- pidc(pidc_output)
#' # look at output
#' head(pidc_parsed)
#' @export

pidc <- function(file_path) {

  if (!file.exists(file_path))
    stop("Please specify a valid file path to ", file_path, "...", .call = FALSE)

  PIDC_output <- suppressMessages(suppressWarnings(readr::read_delim(file = file_path, col_names = FALSE, delim = "\t")))
  names(PIDC_output) <- c("GeneX", "GeneY", "Weight")
  PIDC_output <- PIDC_output[-1,]

  ngenes <- length(unique(PIDC_output$GeneX))
  message("Repairing names...")
  res <- tibble::as_tibble(matrix(NA_real_, ngenes, ngenes), .name_repair = "unique")
  gene_names <- unique(PIDC_output$GeneX)

  colnames(res) <- gene_names
  res <- dplyr::bind_cols(X = gene_names, res)

  res <- as.data.frame(res)


  for (k in 1:length(PIDC_output$Weight)) {

    res[match(PIDC_output[k, 1], gene_names),
        match(PIDC_output[k, 2], gene_names)+1] <- PIDC_output[k, 3]

  }

  colnames(res)[1] <- "Gene"

  result <- data.matrix(res[,2:ncol(res)])

  row.names(result) <- res[,1]

  result[nrow(result), 1] <- result[1, ncol(result)]

  result <- as.matrix(result)

  return(result)
}
