#' @title Output Parser for GRISLI
#' @description This function parses the standard output generated by the BEELINE tool GRISLI.
#' @param file_path a file path to the GRISLI output file generated by BEELINE.
#' @author Sergio Vasquez and Hajk-Georg Drost
#' @examples
#' # path to GRISLI output file
#' genie3_output <- system.file('beeline_examples/GENIE3/outFile.csv', package = 'scNetworkR')
#' # import GENIE3 specific output
#' genie3_parsed <- genie(genie3_output)
#' # look at output
#' head(genie3_parsed)
#' @export

grisli <- function(file_path) {
  if (!file.exists(file_path))
    stop("Please specify a valid file path to ", file_path, "...", .call = FALSE)

  GRISLI_output <-
    suppressMessages(suppressWarnings(
      readr::read_delim(
        file = file_path,
        col_names = TRUE,
        delim = ","
      )
    ))
  GRISLI(GRISLI_output)[1] <- "Gene"

  result <- data.matrix(GRISLI_output[,2:ncol(GRISLI_output)])

  row.names(result) <- GRISLI_output[,1]

  return(result)
}
