#' @title Output Parser for GENIE3
#' @description This function parses the standard output generated by the BEELINE tool GENIE3.
#' @param file_path a file path to the GENIE3 output file generated by BEELINE.
#' @author Sergio Vasquez and Hajk-Georg Drost
#' @examples
#' # path to GENIE3 output file
#' genie3_output <- system.file('beeline_examples/GENIE3/outFile.csv', package = 'edgynode')
#' # import GENIE3 specific output
#' genie3_parsed <- genie(genie3_output)
#' # look at output
#' head(genie3_parsed)
#' @export

genie <- function(file_path) {
  if (!file.exists(file_path))
    stop("Please specify a valid file path to ", file_path, "...", .call = FALSE)

  GENIE3_output <-
    suppressMessages(suppressWarnings(
      readr::read_delim(
        file = file_path,
        col_names = TRUE,
        delim = ","
      )
    ))
  GENIE3_output <- GENIE3_output[-1]
  
  
  first_line <- stringr::str_split(readr::read_lines(file = file_path, n_max = 1), ",")
  genie_col_names <-
    stringr::str_replace_all(noquote(as.vector(unlist(first_line)))[-1], "\"", "")
  
  # names(GENIE3_output)[1] <- "rowname"
  names(GENIE3_output) <- genie_col_names
  GENIE3_output <- dplyr::bind_cols(tibble::tibble(gene_names = genie_col_names), GENIE3_output)
  
  res <- tibble::column_to_rownames(GENIE3_output, var = "gene_names")
  res <- data.matrix(res)
  
  if (!isSymmetric(res))
    warning("The matrix provided as input for genie() was not symmetric.")

  return(res)
}
